package cytoscape.dialogs;

import java.awt.Dimension;

import java.awt.Component;
import java.awt.GridBagConstraints;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JDialog;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JLabel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.Insets;
import java.awt.GridBagLayout;

public class EditNetworkTitleDialog extends JDialog implements ActionListener {
    
    public EditNetworkTitleDialog(Component parent, boolean modal, String pName) {
        super((JFrame)parent, modal);
        initComponents();
        tfNetworkTitle.setText(pName);
        tfNetworkTitle.setSelectionStart(0);
        tfNetworkTitle.setSelectionEnd(pName.length());
        
        setSize(new java.awt.Dimension(300,170));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">
    private void initComponents() {
        GridBagConstraints gridBagConstraints;

        jLabel1 = new JLabel();
        tfNetworkTitle = new JTextField();
        jPanel1 = new JPanel();
        btnOK = new JButton();
        btnCancel = new JButton();

        btnOK.addActionListener(this);
        btnCancel.addActionListener(this);

        getContentPane().setLayout(new GridBagLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Network Title");
        jLabel1.setText("Please enter new network title:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.insets = new Insets(15, 10, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new Insets(10, 10, 10, 10);
        getContentPane().add(tfNetworkTitle, gridBagConstraints);

        btnOK.setText("OK");
        btnOK.setPreferredSize(new Dimension(65, 23));
        btnCancel.setPreferredSize(new Dimension(65, 23));
        
        jPanel1.add(btnOK);

        btnCancel.setText("Cancel");
        jPanel1.add(btnCancel);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new Insets(10, 0, 10, 0);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>
    	 
    public void actionPerformed(ActionEvent e) {
		Object _actionObject = e.getSource();

		// handle Button events
		if (_actionObject instanceof JButton)
		{
			JButton _btn = (JButton)_actionObject;

			if (_btn == btnOK) {				
				networkTitle = tfNetworkTitle.getText();
				this.dispose();
			}
			else if (_btn == btnCancel){
				this.dispose();
			}
		}
    }
    public String getNewNetworkTitle() {
    	return networkTitle;
    }
    private String networkTitle = "";
    
    // Variables declaration - do not modify
    private JButton btnCancel;
    private JButton btnOK;
    private JLabel jLabel1;
    private JPanel jPanel1;
    private JTextField tfNetworkTitle;
    // End of variables declaration
}