/*
 * Logics.java
 *
 * Created on 6 fÃ©vrier 2008, 12:18
 */
package lotrec.gui;

/**
 *
 * @author  said
 */
@Deprecated
public class LogicsPanel extends javax.swing.JPanel {

    final MainFrame mainFrame;

    /** Creates new form Logics */
    public LogicsPanel(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
    }

    public LogicsPanel() {
        this(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createTitledBorder("Loaded Logics"));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 560, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 705, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public lotrec.gui.LoadedLogicsPanel getLoadedLogicsPanel() {
        return new LoadedLogicsPanel(mainFrame);//loadedLogicsPanel;
    }
}
