//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.4-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.01.16 at 04:02:45 PM PST 
//


package cytoscape.generated2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for anchor.type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="anchor.type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="c"/>
 *     &lt;enumeration value="n"/>
 *     &lt;enumeration value="ne"/>
 *     &lt;enumeration value="e"/>
 *     &lt;enumeration value="se"/>
 *     &lt;enumeration value="s"/>
 *     &lt;enumeration value="sw"/>
 *     &lt;enumeration value="w"/>
 *     &lt;enumeration value="nw"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum AnchorType {

    @XmlEnumValue("c")
    C("c"),
    @XmlEnumValue("n")
    N("n"),
    @XmlEnumValue("ne")
    NE("ne"),
    @XmlEnumValue("e")
    E("e"),
    @XmlEnumValue("se")
    SE("se"),
    @XmlEnumValue("s")
    S("s"),
    @XmlEnumValue("sw")
    SW("sw"),
    @XmlEnumValue("w")
    W("w"),
    @XmlEnumValue("nw")
    NW("nw");
    private final String value;

    AnchorType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AnchorType fromValue(String v) {
        for (AnchorType c: AnchorType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
