//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.4-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.01.16 at 04:02:45 PM PST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.cs.rpi.edu/XGMML", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package cytoscape.generated2;
