/*
 * LogicInfoPane.java
 *
 * Created on 29 octobre 2007, 19:36
 */
package lotrec.gui.logicspane;

import java.util.ResourceBundle;
import lotrec.gui.DialogsFactory;
import lotrec.resources.ResourcesProvider;

/**
 *
 * @author  said
 */
public class LogicInfoPanel extends javax.swing.JPanel {

    private LogicDefTab logicDefTab;

    /** Creates new form LogicInfoPane */
    public LogicInfoPanel() {
        initComponents();
    }

    public LogicInfoPanel(LogicDefTab logicDefTab) {
        this.logicDefTab = logicDefTab;
        initComponents();
        displayLogicInfo();
        cancelEdition();
    }

    public void refresh() {
        this.resource = java.util.ResourceBundle.getBundle("lotrec.resources.LoadedLogicsPanel", ResourcesProvider.getCurrentLocale());
        setBorder(javax.swing.BorderFactory.createTitledBorder(resource.getString("LogicDefInfo.title")));
//        lblLogicName.setText(resource.getString("LogicDefInfo.LogicName"));
//        lblDescription.setText(resource.getString("LogicDefInfo.Description"));
//        lblAuthors.setText(resource.getString("LogicDefInfo.Authors"));
//        lblLastUpdate.setText(resource.getString("LogicDefInfo.LastUpdate"));
    }

    public void displayLogicInfo() {
        txaDescription.setText(logicDefTab.getLogic().getDescription());
        txaDescription.setCaretPosition(0);
//        txfAuthors.setText(logicDefTab.getLogic().getAuthor());
//        txfLastUpdate.setText(logicDefTab.getLogic().getLastUpdate());
//        txfLogicName.setText(logicDefTab.getLogic().getName());
    }

//    private void showDetails() {
//        //lblShowHideComments.setText("[--]");
//        lblShowHideComments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotrec/images/hide.png")));
//        innerPanel.setVisible(true);
//    }
//
//    private void hideDetails() {
//        //lblShowHideComments.setText("[+]");
//        lblShowHideComments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotrec/images/show.png")));
//        innerPanel.setVisible(false);
//    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        innerPanel = new javax.swing.JPanel();
        scrlLogicDescription = new javax.swing.JScrollPane();
        txaDescription = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setOpaque(false);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });
        addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                formInputMethodTextChanged(evt);
            }
        });

        innerPanel.setOpaque(false);

        txaDescription.setColumns(20);
        txaDescription.setLineWrap(true);
        txaDescription.setRows(5);
        txaDescription.setText("<logic Description>");
        txaDescription.setWrapStyleWord(true);
        txaDescription.setMargin(new java.awt.Insets(1, 5, 2, 4));
        scrlLogicDescription.setViewportView(txaDescription);

        org.jdesktop.layout.GroupLayout innerPanelLayout = new org.jdesktop.layout.GroupLayout(innerPanel);
        innerPanel.setLayout(innerPanelLayout);
        innerPanelLayout.setHorizontalGroup(
            innerPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(innerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(scrlLogicDescription, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                .addContainerGap())
        );
        innerPanelLayout.setVerticalGroup(
            innerPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, innerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(scrlLogicDescription, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotrec/images/edt.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setToolTipText("Edit Logic Info");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
        jPanel1.add(btnEdit, gridBagConstraints);

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotrec/images/check-16.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.setToolTipText("Save Changes");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
        jPanel1.add(btnSave, gridBagConstraints);

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotrec/images/del.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setToolTipText("Discard Changes");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
        jPanel1.add(btnCancel, gridBagConstraints);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, innerPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(innerPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

//    private void lblShowHideCommentsMouseClicked(java.awt.event.MouseEvent evt) {
//        if (innerPanel.isVisible()) {
//            hideDetails();
//        } else {
//            showDetails();
//        }
//    }

    private void setFieldsEditable(boolean yes) {
        txaDescription.setEditable(yes);
//        txfAuthors.setEditable(yes);
//        txfLastUpdate.setEditable(yes);
//        txfLogicName.setEditable(yes);
    }

    private void startEdition() {
        btnEdit.setEnabled(false);
        btnSave.setEnabled(true);
        btnCancel.setEnabled(true);
//        showDetails();
        setFieldsEditable(true);
    }

    private void saveEdition() {
        //Verify infos
        //if ok 
        //   --> Save info
        //else
        //   --> display the error
        //   --> back toedition
//        System.out.println("new info will be saved... ");
        String desc = txaDescription.getText();
//        String name = txfLogicName.getText();
//        String author = txfAuthors.getText();
//        String lastUpdate = txfLastUpdate.getText();
//        logicDefTab.getLogic().setName(name);
//        logicDefTab.getLogic().setAuthor(author);
//        logicDefTab.getLogic().setLastUpdate(lastUpdate);
        logicDefTab.getLogic().setDescription(desc);
        logicDefTab.setModifiedAndNotSaved(true);
        logicDefTab.getMainFrame().getLoadedLogicsPanel().
                changeLogicNameIfAlreadyUsed(logicDefTab);
//        logicDefTab.getMainFrame().getControlsPanel().refreshLogicsList();
        cancelEdition();
    }

    private void cancelEdition() {
        btnEdit.setEnabled(true);
        btnSave.setEnabled(false);
        btnCancel.setEnabled(false);
        // for the moment, we hide the details, but better
        // they should be brought to the old state
//        hideDetails();
        displayLogicInfo();
        setFieldsEditable(false);
    }

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        
    }//GEN-LAST:event_formFocusLost

    private void formInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_formInputMethodTextChanged
        
    }//GEN-LAST:event_formInputMethodTextChanged

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        startEdition();
}//GEN-LAST:event_btnEditActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        int choice = DialogsFactory.cancelDialog(this);
        if (choice == 0) {
            cancelEdition();
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        saveEdition();
    }//GEN-LAST:event_btnSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel innerPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane scrlLogicDescription;
    private javax.swing.JTextArea txaDescription;
    // End of variables declaration//GEN-END:variables
    private ResourceBundle resource;
}
